### PR TITLE
Implement is_abandoned()

### LINKED ISSUE #41: Implement `is_closed()`?
I've never needed this, but I've seen that it's implemented in:

https://github.com/Ralith/oddio/blob/edfec45801ea88f130cd0be719298b9c12673469/src/spsc.rs#L95-L99

and

https://github.com/Ralith/oddio/blob/edfec45801ea88f130cd0be719298b9c12673469/src/spsc.rs#L134-L138

I guess this could also be implemented with [Arc::strong_count()](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.strong_count).

Does anyone need this?

Are there any downsides to implementing this?

### PR DESCRIPTION
**Pull request by mgeier**
Closes #41.

### CODE REVIEW

**Comment by John-Nagle** [comment]
I was about to request this as a feature.

Use case is in shutting down a game client type system, where various threads which use channels to communicate need to exit. Some threads have no traffic to send during shutdown, so they don't notice that the receiver has exited. is_abandoned() or is_closed() gives them a way to test if the receiver is gone. Intent is a clean exit; all threads exit without panicking or being killed, join their parent, and the system exits normally.

Right now, I send a zero-length message to do that test, and the receiver has to ignore it.

**Comment by mgeier** [comment]
Thanks for chiming in!

Do you think the API in this PR is appropriate?

Other channels use "closed" or "disconnected", but I think "abandoned" is a better fit because this can also happen quite passively and there is no method `close()` or `disconnect()`.

I've just realized that I didn't properly check some `Result`s in the code examples, which I have done now: f69678663139db3711828025c1fcffe3ec03976d

A ZIP file with the generated HTML files is available at https://github.com/mgeier/rtrb/suites/2692114073/artifacts/59326860.

**Comment by John-Nagle** [comment]
No strong opinion. I was going to suggest **is_open()**, indicating that as of that moment, sends were still possible.

**Comment by mgeier** [comment]
> I was going to suggest **is_open()**, indicating that as of that moment, sends were still possible.

I have the feeling that this might suggest a behavior that's not actually guaranteed. If `Producer::is_open()` returns `true`, the `Consumer` might just be dropped in a different thread, meaning that subsequent sends will never reach the consumer.

```rust
if p.is_open() {
    // the channel might be open, but it might also just have been closed
}

if p.is_abandoned() {
    // the channel is definitely abandoned and will stay that way
}
```

In fact, there is never a guarantee that anything reaches the consumer, because the consumer isn't forced to read anything. There can only be a guarantee that something does *not* reach the consumer.

As a counter argument, one could say that this is the exact behavior of `is_full()` and `is_empty()`, which means they should actually be used in their negated form:

```rust
if !p.is_full() {
    // I'm guaranteed to be able to write at least one item
}
```

I don't know ... what do you think?

**Comment by mgeier** [comment]
To avoid surprises, I've updated the documentation: f2c05e8546f4fc0c9caa30e328e81e0032a7ac33.

I've also added documentation for `is_empty()` and `is_full()`: #53

**Pull request merged**
